### ISSUE TITLE
help project

### ISSUE THREAD

**Issue by michelNice** [DejanSheki/ip-address-tracker-master#1]
Hello there! how are you?

I have been trying to build a project but I can not get the navegation the right way. So What i am trying to do is add  an unorder list  a h2 with flexbox. my goal is

1. scroll down and the IMG shrink  without move the unorder list around as well as the text.
2. when it goes to mobile the ima has to be with no shrink at all

my code:https://github.com/michelNice/Nest-Panos

exemple what I wanna it:https://www.nestpanos.com

**Comment by DejanSheki** [comment]
Hi,

1. for IMG container add fixed width, something like that:

 ```css
.fixed-container {
  width: 300px;
  display: flex;
  justify-content: center;
}
```
or navbar  justify-content: space-between;

2. I am not sure, I'm not using jQuery but there is a lot of tutorials on web
